/**
 * Player identity pool
 * --------------------
 * List of display names users may select as their in-game identity.
 * This is intentionally decoupled from authentication and persistence.
 */
export const PLAYER_NAMES = [
  "Aiman",
  "Ambareen",
  "Aarush",
  "Agneesh",
  "Arpan Mukherjee",
  "Arpan Roy",
  "Arsalan",
  "Ayesha",
  "Debraj",
  "Deboparni",
  "Durga",
  "Farhan",
  "Harsh",
  "Jayakumari",
  "Kasifa",
  "Krishna",
  "Mohamman",
  "Nuran Ali",
  "Om",
  "Rashid",
  "Riddhi",
  "Ritarshi",
  "Rubel",
  "Rudra",
  "Rudranil",
  "Rupsa",
  "Sama",
  "Sariya",
  "Sartaz",
  "Shreya",
  "Sifa",
  "Smita",
  "Sounen",
  "Soumyajit",
  "Srishti",
  "Subhadeep",
  "Subhodeep Xalindi",
  "Subhradip",
  "Subhranil",
  "Shubhadeep Mahato",
  "Suman Sengupta",
  "Syed Nabeel",
  "Tara",
  "Tarak Nath",
  "Zainab",
  "Zeeshan",
];
